Controllers/PicturesController.cs
using AdminPanel.Models;
using AdminPanel.Services;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace AdminPanel.Controllers
{
    public class PicturesController : Controller
    {
        PicturesService PicturesService;
        public PicturesController(ApplicationContext context, IWebHostEnvironment env)
        {
            PicturesService = new PicturesService(context);
        }
        public IActionResult PicturesEdit()
        {
            var listPictures = PicturesService.GetAll();
            return View(listPictures);
        }
        public IActionResult DeletePicture([FromForm] Pictures picturesID)
        {
            //Получить айди фото для удаления
            PicturesService.Delete(picturesID);
            return RedirectToAction("Index", "News");
        }
    }
}

Views/Pictures/PicturesEdit.cshtml
 @model List<Pictures>
 <div class="main--galary">
<a href="@Url.ActionLink("Index", "News")"><button>Назад</button></a>
@foreach(var pictures in Model)
{
    <div class="galary">        
        <div class="block"><img src="@pictures.FilePath">
            @using (Html.BeginForm("DeletePicture", "Pictures", new { }))

                {
                    <button class="galary--button" name="Id" value="@pictures.Id">удалить</button>
                }
            <button class="galary--button">сделать главным</button></div></div>
    
}
</div>
<style>
    .main--galary{
        display:flex;
        justify-content:space-evenly;
        flex-direction:row;
    }
   
</style>